version: 2
project_name: cloud-functions-pp-cli
changelog:
  disable: true
builds:
  - id: cloud-functions-pp-cli
    main: ./cmd/cloud-functions-pp-cli
    binary: cloud-functions-pp-cli
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X cloud-functions-pp-cli/internal/cli.version={{ .Version }}
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64
  - id: cloud-functions-pp-mcp
    main: ./cmd/cloud-functions-pp-mcp
    binary: cloud-functions-pp-mcp
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64
archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
checksum:
  name_template: checksums.txt
brews:
  - name: cloud-functions-pp-cli
    repository:
      owner: shubhan-yenuganti
      name: homebrew-tap
    homepage: "https://github.com/shubhan-yenuganti/cloud-functions-pp-cli"
    description: "Manages lightweight user-provided functions executed in response to events."
    install: |
      bin.install "cloud-functions-pp-cli"
      bin.install "cloud-functions-pp-mcp"
